- cert-spec.txt
- rend-spec-v3.txt
Pointed out by inkylatenoth in:
https://lists.torproject.org/pipermail/tor-dev/2017-October/012527.html
Fixes ticket #24544.
> Fix inconsistencies on HS v3 spec and cert-spec.txt.

- control-spec.txt
https://trac.torproject.org/projects/tor/ticket/25852
> Document error handling for #25852

- control-spec.txt
https://trac.torproject.org/projects/tor/ticket/26211
https://trac.torproject.org/projects/tor/ticket/8323
> Document GETINFO md/all

- bandwidth-file-spec.txt
also, update sbws examples
Fixes #26200
> Add bw lines KeyValues counting failures

- control-spec.txt
https://trac.torproject.org/projects/tor/ticket/26903
> #26903: Document all of GETINFO net/listeners/*

- rend-spec-v3.txt
Pointed out by Jean Chevalier.
> HSv3: Actually do base32 in the client auth pubkey example.

- bandwidth-file-spec.txt
It explains in a different way section 2.2 in torflow's
README.spec.txt.
> Add torflow scaling section

- control-spec.txt
With the changes of ticket 27167, we need to describe the new set of
bootstrap phases.
XXX still needs more detailed descriptions of some things.
> WIP Update bootstrap phases for 0.4.0.x

- control-spec.txt
https://trac.torproject.org/projects/tor/ticket/28757
> #28757: Stop mentioning 'GETINFO status/version/num-{concurring,versioning}'

- control-spec.txt
For the bug [here](https://trac.torproject.org/projects/tor/ticket/25417).
> [Tor Trac #25417]: HSFETCH support for v3 Hidden Services

- control-spec.txt
Also add an overview of bootstrap reporting, and divide phases into
three stages.
Part of ticket 28928.
> WIP ticket28928 Details for new 0.4.0.x bootstrap phases

- bandwidth-file-spec.txt
> bandwidth-file: Fix a typo, the file is not a fallback file

- bandwidth-file-spec.txt
in some of the Bandwidth Line KeyValues.
Closes #29814.
> bandwidth-file: Replace mistaken NL by SP

- dir-spec.txt
> dir-spec: Update the Tor version for bandwidth-file-digest

- control-spec.txt
For the bug [here](https://trac.torproject.org/projects/tor/ticket/28269).
> [Tor Trac #28269]: Add HSFETCH controller response QUERY_RATE_LIMITED

- cert-spec.txt
https://trac.torproject.org/projects/tor/ticket/30119
> #30119: Mention that we're using NBO in cert-spec.txt

- rend-spec-v3.txt
> rend-v3: single onion services retry intro and rend with 3-hop paths

- proposals/306-ipv6-happy-eyeballs.txt
> Prop306 squashed

- control-spec.txt
https://trac.torproject.org/projects/tor/ticket/31081
> #31081: Document that Tor accepts GETCONF with zero or more arguments

- bandwidth-file-spec.txt
> bandwidth-file: Add tor_version header

- tor-spec.txt
With minor edits from the draft in proposal 311.
Closes ticket 33227.
> tor-spec: Add Relay=3 protocol version

- dir-spec.txt
Code pull request: https://github.com/torproject/tor/pull/1923
> [Tor Trac #7869]: Remove padding from ntor-onion-key
