torproject/torspec

- control-spec.txt
This is on top of the existing PR #5.
>  Fix spelling errors in control-spec.txt

- dir-spec.txt
The descriptor would be updated on bandwidth changes only when
the uptime is less than 24h.
> Include uptime in bandwidth changes event

- rend-spec-v3.txt
It's meant to protect against entities that don't know the identity public
key (aka the onion address).
Closes #26379. Pointed out by Steven Murdoch.
> rend-spec-v3.txt: Clarify role of first layer desc encryption.

- bandwidth-file-spec.txt
Add MaxAdvertisedBandwidth section in the bw KeyValue and explain
why measured bandwidths need to be limited to it and how current
implementations do it.
Co-authored-by: teor <teor2345@gmail.com>
> bandwidth-file-spec: add MaxAdvertisedBandwidth

- tor-spec.txt
This branch fixes these Trac tickets:
https://trac.torproject.org/projects/tor/ticket/26893
https://trac.torproject.org/projects/tor/ticket/26894
> CREATE/CREATE2; all-zeroes fingerprints

- control-spec.txt
Do not mention "non-transient internal error" as it is extremely
unlikely to happen.
https://trac.torproject.org/projects/tor/ticket/27034
> #27034: Simplify explanation of GETINFO exit-policy/*

- dir-spec.txt
Remove the header's Keywords in the bandwidth-file-headers item,
since they are described in bandwidth-file-spec.txt and we should
not need to update two specifications every time they change.
> dir-spec: remove Keywords in bandwidth-file-headers

- tor-spec.txt
Let's refrain from mentioning section 6.4 in here, as the format
is not exactly the same - not all address type field values from
section 6.4 make sense in NETINFO cell and NETINFO cell does not
have a TTL value at the end of each address. It's a little confusing
to suggest that there is a reuse of wire format fragment between
RELAY_RESOLVED and NETINFO cells.
> #27325: Reword address format definition in section 4.5

- dir-spec.txt
The extra-info-digest field of server descriptors was defined to contain
either a SHA1, or a SHA1 and a SHA256 digest. These were both meant to
be computed over the same data but due to an implementation error, the
Tor network has been computing the digests over different data for a
while. This is a lot easier to fix in the spec than in the code, and
the error does not seem to cause any harm beyond being a little
confusing (which this patch should help with).
A minor fix is also made to the SHA1 digest portion of the text. This is
a typo fix and a clarification, and does not change the semantic meaning
for that portion.
> dir-spec: Make extra-info-digest reflect reality

- dir-spec.txt
tor does not generate ns consensuses that are explicitly labelled as ns
consensuses. This updates the spec to make the flavor portion optional,
and to allow the assumption to be made that if a flavor is omitted from
the "network-status-version" line then it is "ns".
One "flavour" was also turned into a "flavor" for consistency.
> dir-spec: The ns consensus isn't explicitly ns

- proposals/299-ip-failure-count.txt
Was requested [here](https://lists.torproject.org/pipermail/tor-dev/2019-March/013730.html).
> New version of Preferring IPv4 or IPv6 based on IP Version Failure Count.

- dir-spec.txt
We increased the bandwidth statistics period in 23856 to improve privacy.
This change also increased the observed bandwidth period.
Closes bug 28984.
> dir-spec: Update observed bandwidth period to 5 days

- dir-spec.txt
From Tor 0.4.0.4-alpha, bandwidth files are available via HTTP,
but the Tor version in which it first appeared was wrong.
Fixes #26694.
> dir-spec: Update bandwidth files URL Tor URL

- bandwidth-file-spec.txt
in the nonterminals definition, so that it match implementations
and does not fail with a grammar parser.
Closes: #30373
> bandwidth-file: Replace KeyWord by Key

- control-spec.txt
> control-spec: Document logs that are not included in the Log event

- control-spec.txt
Ticket 31684 adds support for GETINFO
dir/status-vote/current/consensus-microdesc as of Tor 0.4.3.1-alpha.
Closes 31762.
> control: Add GETINFO dir/status-vote/current/consensus-microdesc

- bandwidth-file-spec.txt
- bridgedb-spec.txt
- cert-spec.txt
- control-spec.txt
- dir-list-spec.txt
- dir-spec.txt
- gettor-spec.txt
- glossary.txt
- guard-spec.txt
- padding-spec.txt
- path-spec.txt
- pt-spec.txt
- rend-spec-v3.txt
- socks-extensions.txt
- srv-spec.txt
- tor-fw-helper-spec.txt
- tor-spec.txt
This fixes a handful of errors in the syntax of things like the title line and the section names.  That makes these files much more machine readable.  All of the changes here are trivial.
With these changes, then a script can convert these files to a nice collection of HTML pages in a CI job that takes less than a minute to run:
* https://gitlab.com/eighthave/torspec/-/jobs/362125193
* https://eighthave.gitlab.io/torspec/
This provides nice features like links to sections based on the section name:
* https://eighthave.gitlab.io/torspec/control-spec.html#hsfetch
* https://eighthave.gitlab.io/torspec/control-spec.html#circuit-status-changed
* https://eighthave.gitlab.io/torspec/tor-spec.html#tls-security-considerations
Using GitLab CI, this could easily rsync the result to any webserver.
> Bug32619:  fix syntax errors in torspec documents 

- .gitlab-ci.yml
- bridgedb-spec.txt
- control-spec.txt
- dir-list-spec.txt
- dir-spec.txt
- guard-spec.txt
- padding-spec.txt
- path-spec.txt
- rend-spec-v2.txt
- rend-spec-v3.txt
- srv-spec.txt
- tor-spec.txt
- version-spec.txt
This does a rough conversion to Markdown using regexps, then uses pandoc to convert the Markdown to HTML.  An index.html is also generated to make it easy to find the various documents.  This will create a site in any GitLab fork that has CI/CD and Pages setup, which is the default on gitlab.com.
Here's an example:
* https://gitlab.com/eighthave/torspec/-/jobs/362186659
* https://eighthave.gitlab.io/torspec/
> Bug32627: build HTML GitLab Pages site with GitLab CI

- dir-list-spec.txt
* Rename "whitelist" to "offer-list" for 32699.
* Add "descriptor" for 24839.
* Allow multiple values for the 24839 transition to signed offers
in descriptors.
Part of 32699 and 24839.
> dir-list-spec: Modify "source=" line format

- proposals/reindex.py
Add the standard future statements, so Python 2 will use some
Python 3 features.
Decode lines as UTF-8. As a consequence of this change, proposals
must be encoded in UTF-8.
Closes ticket 33164.
> proposals: Update reindex.py for Python 3

- dir-spec.txt
See [ticket 33573](https://trac.torproject.org/projects/tor/ticket/33573).
This value of 12 hours was change in ​commit torproject/tor@cc351578 to 2 hours.
> dir-spec: descriptor differences are cosmetic if 2 hours, not 12 hours

- control-spec.txt
This patch adds and documents the purposes HS_VANGAURD,
PATH_BIAS_TESTING, and CIRCUIT_PADDING.
Closes ticket 33640.
> Control-spec.txt: add several circuit purposes
